defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "DOME_SSO"
    footer_text: "Powered by <a href=\"http://domelab.com/\">DOME</a>"

development:
  <<: *defaults
  authenticators:
    user_table:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "mysql2"
          host: "localhost"
          username: "root"
          password: "your_password"
          database: "dome_sso_dev"
        table: "users"
        username_column: "name"
        password_column: "password_digest"
        extra_attributes:
          email: "email"
          nickname: "name"
          mobile: "phone"
          confirmed: "confirmed"
          guid: "id"

test:
  <<: *defaults
  authenticators:
    auth_user_by_name:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "mysql2"
          host: "localhost"
          username: "root"
          password: "your_password"
          database: "dome_sso_dev"
        table: "users"
        username_column: "name"
        password_column: "password_digest"
        extra_attributes:
          email: "email"

production:
  <<: *defaults
  authenticators:
    auth_user_by_name:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "mysql2"
          host: "localhost"
          username: "root"
          password: "your_password"
          database: "dome_sso_dev"
        table: "users"
        username_column: "name"
        password_column: "password_digest"
        extra_attributes:
          email: "email"
