email:
  account: "bikeman18@163.com"
  password: "163cn100c"
  domain: "163.com"
allow_from: ["http://www.c1.com/","http://www.c2.com/"]
submail:
  sms_config:
    appid: "11647"
    signature: "7a2d779109b4cb662ca10781f967f772"
    project: "PCGQk2"
